name: Zip and Upload to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./backend

      - name: Zip the code
        run: |
          cd path/to/your/code
          zip -r my_code.zip .
        working-directory: ./backend

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.2.1
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY}}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        working-directory: ./backend
