name: Zip and Upload to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # - name: Install dependencies
      #   working-directory: ./backend
      #   run: |
      #     pip install --upgrade pip
      #     pip install -r requirements.txt
          
      # - name: Clear Cache
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/backend/.cache/pip
      #   if: ${{ failure() }}

      - name: Zip the code
        working-directory: ./backend
        run: |
          cd $GITHUB_WORKSPACE/backend
          zip -r rsvp_lambda_code.zip .

      - name: Empty S3 Bucket
        if: success()
        run: aws s3 rm s3://${{ secrets.AWS_S3_BUCKET }} --recursive

      - name: Upload to S3
        if: success()
        run: aws s3 cp ./backend/rsvp_lambda_code.zip s3://${{ secrets.AWS_S3_BUCKET }}

      - name: Update Lambda code
        if: success()
        run: aws lambda update-function-code --function-name=rsvp_service --zip-file=fileb://backend/rsvp_lambda_code.zip
