name: WebApp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY}}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          
      - name: Set API key
        working-directory: ./RSVP-WebApp
        run: |
         echo "export const environment = {
          production: true,
          apiUrl: '${{ secrets.API_URL }}',
          firebase: {
            apiKey: '${{ secrets.FIREBASE_API_KEY }}',
            authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
            projectId: '${{ secrets.FIREBASE_PROJECTID }}',
            storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
            messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
            appId: '${{ secrets.FIREBASE_APP_ID }}',
            persistence: '${{ secrets.FIREBASE_PERSISTENCE }}'
            },
          };" > src/environments/environment.ts

      - name: Install dependencies
        working-directory: ./RSVP-WebApp
        run: npm install

      - name: Build
        working-directory: ./RSVP-WebApp
        run: npm run build

      - name: Deploy
        if: success()
        run: aws s3 sync ./RSVP-WebApp/dist/rsvp-web-app s3://${{ secrets.AWS_WEB_S3_BUCKET }}
