name: WebApp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY}}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main  # Specify the branch directly

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get Private Script
        uses: actions/checkout@v2
        with:
          repository: raboomar/weddingRSVPENVVars  # Replace with your private repository information
          path: private-scripts  # Specify a path where the private script is located
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Run Private Script (TypeScript)
        run: |
          chmod +x private-scripts/generate-environment.ts
          node private-scripts/generate-environment.ts
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Install dependencies
        working-directory: ./RSVP-WebApp
        run: npm install

      - name: Build
        working-directory: ./RSVP-WebApp
        run: npm run build

      - name: Deploy
        if: success()
        run: aws s3 sync ./RSVP-WebApp/dist/rsvp-web-app s3://${{ secrets.AWS_WEB_S3_BUCKET }}
