name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: ./RSVP-WebApp
        run: npm install

      - name: Build
        working-directory: ./RSVP-WebApp
        run: npm run build
      - name: Debug
        run: |
          ls -l ./RSVP-WebApp
          ls -l ./RSVP-WebApp/dist
      - name: Deploy
        if: success()
        run: aws s3 sync ./RSVP-WebApp/dist/RSVP s3://dima-rami-rsvp-app.s3
